def prune_domaintools_expected():
    return {'has_more_results': False,
            'limit_exceeded': False,
            'message': 'Enjoy your data.',
            'results': [{'active': True,
                         'additional_whois_email': [{'count': 12707979,
                                                     'value': 'abuse@enom.com'}],
                         'admin_contact': {'city': {'count': 91124643,
                                                    'value': 'REDACTED FOR PRIVACY'},
                                           'country': {'count': 88204165,
                                                       'value': 'REDACTED FOR PRIVACY'},
                                           'name': {'count': 92404141,
                                                    'value': 'REDACTED FOR PRIVACY'},
                                           'org': {'count': 89136737,
                                                   'value': 'REDACTED FOR PRIVACY'},
                                           'postal': {'count': 92056029,
                                                      'value': 'REDACTED FOR PRIVACY'},
                                           'state': {'count': 87938445,
                                                     'value': 'REDACTED FOR PRIVACY'},
                                           'street': {'count': 87214024,
                                                      'value': 'REDACTED FOR PRIVACY'}},
                         'alexa': 2558,
                         'create_date': {'count': 881, 'value': '1998-08-02'},
                         'data_updated_timestamp': '2022-06-09T16:05:01.373000',
                         'domain': 'domaintools.com',
                         'domain_risk': {'components': [{'name': 'zerolist',
                                                         'risk_score': 0}],
                                         'risk_score': 0},
                         'email_domain': [{'count': 22145613, 'value': 'enom.com'},
                                          {'count': 4440523, 'value': 'nsone.net'}],
                         'expiration_date': {'count': 2111, 'value': '2027-08-01'},
                         'ip': [{'address': {'count': 4, 'value': '199.30.228.112'},
                                 'asn': [{'count': 111, 'value': 17318}],
                                 'country_code': {'count': 292833707, 'value': 'US'},
                                 'isp': {'count': 222, 'value': 'DomainTools LLC'}}],
                         'mx': [{'domain': {'count': 23496110, 'value': 'google.com'},
                                 'host': {'count': 20042665,
                                          'value': 'aspmx.l.google.com'},
                                 'ip': [{'count': 3595011, 'value': '74.125.142.26'}],
                                 'priority': 1},
                                {'domain': {'count': 8166213, 'value': 'googlemail.com'},
                                 'host': {'count': 7072286,
                                          'value': 'aspmx3.googlemail.com'},
                                 'ip': [{'count': 9090245, 'value': '142.250.115.26'}],
                                 'priority': 10},
                                {'domain': {'count': 23496110, 'value': 'google.com'},
                                 'host': {'count': 19646081,
                                          'value': 'alt1.aspmx.l.google.com'},
                                 'ip': [{'count': 5621039, 'value': '142.250.141.27'}],
                                 'priority': 5},
                                {'domain': {'count': 8166213, 'value': 'googlemail.com'},
                                 'host': {'count': 7195048,
                                          'value': 'aspmx2.googlemail.com'},
                                 'ip': [{'count': 5621039, 'value': '142.250.141.27'}],
                                 'priority': 10},
                                {'domain': {'count': 23496110, 'value': 'google.com'},
                                 'host': {'count': 19558282,
                                          'value': 'alt2.aspmx.l.google.com'},
                                 'ip': [{'count': 9090245, 'value': '142.250.115.26'}],
                                 'priority': 5},
                                {'domain': {'count': 8166213, 'value': 'googlemail.com'},
                                 'host': {'count': 1534382,
                                          'value': 'aspmx4.googlemail.com'},
                                 'ip': [{'count': 7395079, 'value': '64.233.171.26'}],
                                 'priority': 10}],
                         'name_server': [{'domain': {'count': 2983519,
                                                     'value': 'nsone.net'},
                                          'host': {'count': 368900,
                                                   'value': 'dns4.p04.nsone.net'},
                                          'ip': [{'count': 368871,
                                                  'value': '198.51.45.68'}]},
                                         {'domain': {'count': 2983519,
                                                     'value': 'nsone.net'},
                                          'host': {'count': 367050,
                                                   'value': 'dns1.p04.nsone.net'},
                                          'ip': [{'count': 367054,
                                                  'value': '198.51.44.4'}]},
                                         {'domain': {'count': 2983519,
                                                     'value': 'nsone.net'},
                                          'host': {'count': 367056,
                                                   'value': 'dns2.p04.nsone.net'},
                                          'ip': [{'count': 367057,
                                                  'value': '198.51.45.4'}]},
                                         {'domain': {'count': 2983519,
                                                     'value': 'nsone.net'},
                                          'host': {'count': 366863,
                                                   'value': 'dns3.p04.nsone.net'},
                                          'ip': [{'count': 366824,
                                                  'value': '198.51.44.68'}]}],
                         'popularity_rank': 4043,
                         'registrant_contact': {'city': {'count': 91124643,
                                                         'value': 'REDACTED FOR PRIVACY'},
                                                'country': {'count': 232689304,
                                                            'value': 'us'},
                                                'name': {'count': 92404141,
                                                         'value': 'REDACTED FOR PRIVACY'},
                                                'org': {'count': 89136737,
                                                        'value': 'REDACTED FOR PRIVACY'},
                                                'postal': {'count': 92056029,
                                                           'value': 'REDACTED FOR '
                                                                    'PRIVACY'},
                                                'state': {'count': 8678667, 'value': 'WA'},
                                                'street': {'count': 87214024,
                                                           'value': 'REDACTED FOR '
                                                                    'PRIVACY'}},
                         'registrant_name': {'count': 92696177,
                                             'value': 'REDACTED FOR PRIVACY'},
                         'registrant_org': {'count': 35243392,
                                            'value': 'REDACTED FOR PRIVACY'},
                         'registrar': {'count': 4040099, 'value': 'ENOM, INC.'},
                         'registrar_status': ['clienttransferprohibited'],
                         'soa_email': [{'count': 4884279,
                                        'value': 'hostmaster@nsone.net'}],
                         'ssl_info': [{'hash': {'count': 1,
                                                'value': 'f8bf8d63eef2c146533bc705d78815a188db8dde'},
                                       'organization': {'count': 1,
                                                        'value': 'DomainTools, LLC'},
                                       'subject': {'count': 1,
                                                   'value': 'CN=domaintools.com,O=DomainTools, '
                                                            'LLC,ST=Washington,C=US,businessCategory=Private '
                                                            'Organization,jurisdictionST=Delaware,jurisdictionC=US,serialNumber=4710432'}}],
                         'technical_contact': {'city': {'count': 91124643,
                                                        'value': 'REDACTED FOR PRIVACY'},
                                               'country': {'count': 88204165,
                                                           'value': 'REDACTED FOR '
                                                                    'PRIVACY'},
                                               'name': {'count': 92404141,
                                                        'value': 'REDACTED FOR PRIVACY'},
                                               'org': {'count': 89136737,
                                                       'value': 'REDACTED FOR PRIVACY'},
                                               'postal': {'count': 92056029,
                                                          'value': 'REDACTED FOR PRIVACY'},
                                               'state': {'count': 87938445,
                                                         'value': 'REDACTED FOR PRIVACY'},
                                               'street': {'count': 87214024,
                                                          'value': 'REDACTED FOR '
                                                                   'PRIVACY'}},
                         'tld': 'com',
                         'website_response': 500,
                         'whois_url': 'https://whois.domaintools.com/domaintools.com'}],
            'results_count': 1,
            'total_count': 1}
