def prune_espn_expected():
    return {'has_more_results': False,
     'limit_exceeded': False,
     'message': 'Enjoy your data.',
     'results': [{'active': True,
                  'additional_whois_email': [{'count': 1573632,
                                              'value': 'domainabuse@cscglobal.com'}],
                  'admin_contact': {'city': {'count': 110095, 'value': 'Bristol'},
                                    'country': {'count': 189951325, 'value': 'us'},
                                    'email': [{'count': 1356,
                                               'value': 'domreg@espn.com'}],
                                    'fax': {'count': 1379, 'value': '18607664502'},
                                    'name': {'count': 1, 'value': 'ESPN, Inc.'},
                                    'org': {'count': 1, 'value': 'ESPN, Inc.'},
                                    'phone': {'count': 1034,
                                              'value': '18607662000'},
                                    'postal': {'count': 1387,
                                               'value': '06010-1001'},
                                    'state': {'count': 560553, 'value': 'CT'}},
                  'alexa': 183,
                  'create_date': {'count': 31, 'value': '1994-10-04'},
                  'data_updated_timestamp': '2020-04-14T09:09:06',
                  'domain': 'espn.com',
                  'domain_risk': {'components': [{'name': 'allowlist',
                                                  'risk_score': 0}],
                                  'risk_score': 0},
                  'email_domain': [{'count': 1420, 'value': 'espn.com'},
                                   {'count': 1813887, 'value': 'cscglobal.com'}],
                  'expiration_date': {'count': 729160, 'value': '2020-10-03'},
                  'ip': [{'address': {'count': 5833, 'value': '13.224.13.26'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 14091796,
                                  'value': 'Amazon Technologies Inc.'}},
                         {'address': {'count': 5912, 'value': '13.224.13.62'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 14091796,
                                  'value': 'Amazon Technologies Inc.'}},
                         {'address': {'count': 5953, 'value': '13.224.13.66'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 14091796,
                                  'value': 'Amazon Technologies Inc.'}},
                         {'address': {'count': 6197, 'value': '13.224.13.80'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 14091796,
                                  'value': 'Amazon Technologies Inc.'}},
                         {'address': {'count': 5879, 'value': '99.86.32.125'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 5530009, 'value': 'Amazon.com Inc.'}},
                         {'address': {'count': 5794, 'value': '99.86.32.27'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 5530009, 'value': 'Amazon.com Inc.'}},
                         {'address': {'count': 5452, 'value': '99.86.32.32'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 5530009, 'value': 'Amazon.com Inc.'}},
                         {'address': {'count': 6100, 'value': '99.86.32.4'},
                          'asn': [{'count': 15806987, 'value': 16509}],
                          'country_code': {'count': 333903806, 'value': 'us'},
                          'isp': {'count': 5530009, 'value': 'Amazon.com Inc.'}}],
                  'mx': [{'domain': {'count': 9083544, 'value': 'outlook.com'},
                          'host': {'count': 1,
                                   'value': 'espn-com.mail.protection.outlook.com'},
                          'ip': [{'count': 435650, 'value': '104.47.45.36'},
                                 {'count': 432743, 'value': '104.47.44.36'}],
                          'priority': 10}],
                  'name_server': [{'domain': {'count': 52299,
                                              'value': 'awsdns-02.org'},
                                   'host': {'count': 5945,
                                            'value': 'ns-1045.awsdns-02.org'},
                                   'ip': [{'count': 6052,
                                           'value': '205.251.196.21'}]},
                                  {'domain': {'count': 49898,
                                              'value': 'awsdns-15.com'},
                                   'host': {'count': 6026,
                                            'value': 'ns-122.awsdns-15.com'},
                                   'ip': [{'count': 6199,
                                           'value': '205.251.192.122'}]},
                                  {'domain': {'count': 8440243, 'value': 'co.uk'},
                                   'host': {'count': 6183,
                                            'value': 'ns-1936.awsdns-50.co.uk'},
                                   'ip': [{'count': 6273,
                                           'value': '205.251.199.144'}]},
                                  {'domain': {'count': 48670,
                                              'value': 'awsdns-41.net'},
                                   'host': {'count': 6826,
                                            'value': 'ns-846.awsdns-41.net'},
                                   'ip': [{'count': 6838,
                                           'value': '205.251.195.78'}]}],
                  'redirect': {'count': 454, 'value': 'espn.go.com'},
                  'redirect_domain': {'count': 62216, 'value': 'go.com'},
                  'registrant_contact': {'city': {'count': 110095,
                                                  'value': 'Bristol'},
                                         'country': {'count': 189951325,
                                                     'value': 'us'},
                                         'email': [{'count': 1354,
                                                    'value': 'domreg@espn.com'}],
                                         'fax': {'count': 1379,
                                                 'value': '18607664502'},
                                         'name': {'count': 1,
                                                  'value': 'ESPN, Inc.'},
                                         'org': {'count': 1, 'value': 'ESPN, Inc.'},
                                         'phone': {'count': 1034,
                                                   'value': '18607662000'},
                                         'postal': {'count': 1387,
                                                    'value': '06010-1001'},
                                         'state': {'count': 560553, 'value': 'CT'}},
                  'registrant_name': {'count': 1, 'value': 'ESPN, Inc.'},
                  'registrant_org': {'count': 1, 'value': 'ESPN, Inc.'},
                  'registrar': {'count': 1, 'value': 'CSC CORPORATE DOMAINS, INC.'},
                  'registrar_status': ['clienttransferprohibited '
                                       'serverdeleteprohibited '
                                       'servertransferprohibited '
                                       'serverupdateprohibited'],
                  'soa_email': [{'count': 3232212,
                                 'value': 'awsdns-hostmaster@amazon.com'}],
                  'spf_info': 'v=spf1 include:servers.mcsv.net mx '
                              'ip4:74.123.203.125 ip4:74.123.200.120 '
                              'ip4:74.123.200.35 ip4:74.123.200.36 '
                              'ip4:74.123.203.98 ip4:74.123.200.222 '
                              'include:_spf.emailcampaigns.net '
                              'include:spf1.worldapp.com ~all',
                  'ssl_info': [{'hash': {'count': 2,
                                         'value': 'f56f5316dc0b40c8ec6e70221d38b2551e90e85a'},
                                'organization': {'count': 9505,
                                                 'value': 'The Walt Disney '
                                                          'Company'},
                                'subject': {'count': 2,
                                            'value': 'CN=espn.com,O=The Walt '
                                                     'Disney '
                                                     'Company,L=Burbank,ST=California,C=US'}},
                               {'hash': {'count': 1,
                                         'value': 'a5b3d9312bce1157b61d53d864d33ee2b226d4e2'},
                                'subject': {'count': 1,
                                            'value': 'CN=redirect.espn.com'}}],
                  'technical_contact': {'city': {'count': 110095,
                                                 'value': 'Bristol'},
                                        'country': {'count': 189951325,
                                                    'value': 'us'},
                                        'email': [{'count': 1355,
                                                   'value': 'domreg@espn.com'}],
                                        'fax': {'count': 1379,
                                                'value': '18607664502'},
                                        'name': {'count': 1, 'value': 'ESPN, Inc.'},
                                        'org': {'count': 1, 'value': 'ESPN, Inc.'},
                                        'phone': {'count': 1034,
                                                  'value': '18607662000'},
                                        'postal': {'count': 1387,
                                                   'value': '06010-1001'},
                                        'state': {'count': 560553, 'value': 'CT'}},
                  'tld': 'com',
                  'website_response': 500,
                  'whois_url': 'https://whois.domaintools.com/espn.com'}],
     'results_count': 1,
     'total_count': 1}