import json


def domaintools():
    json_response = """
    {"limit_exceeded":false,"has_more_results":false,"message":"Enjoy your data.","results_count":1,"total_count":1,"results":[{"domain":"domaintools.com","whois_url":"https:\/\/whois.domaintools.com\/domaintools.com","adsense":{"value":"","count":0},"alexa":2558,"popularity_rank":4043,"active":true,"google_analytics":{"value":"","count":0},"admin_contact":{"name":{"value":"REDACTED FOR PRIVACY","count":92404141},"org":{"value":"REDACTED FOR PRIVACY","count":89136737},"street":{"value":"REDACTED FOR PRIVACY","count":87214024},"city":{"value":"REDACTED FOR PRIVACY","count":91124643},"state":{"value":"REDACTED FOR PRIVACY","count":87938445},"postal":{"value":"REDACTED FOR PRIVACY","count":92056029},"country":{"value":"REDACTED FOR PRIVACY","count":88204165},"phone":{"value":"","count":0},"fax":{"value":"","count":0},"email":[]},"billing_contact":{"name":{"value":"","count":0},"org":{"value":"","count":0},"street":{"value":"","count":0},"city":{"value":"","count":0},"state":{"value":"","count":0},"postal":{"value":"","count":0},"country":{"value":"","count":0},"phone":{"value":"","count":0},"fax":{"value":"","count":0},"email":[]},"registrant_contact":{"name":{"value":"REDACTED FOR PRIVACY","count":92404141},"org":{"value":"REDACTED FOR PRIVACY","count":89136737},"street":{"value":"REDACTED FOR PRIVACY","count":87214024},"city":{"value":"REDACTED FOR PRIVACY","count":91124643},"state":{"value":"WA","count":8678667},"postal":{"value":"REDACTED FOR PRIVACY","count":92056029},"country":{"value":"us","count":232689304},"phone":{"value":"","count":0},"fax":{"value":"","count":0},"email":[]},"technical_contact":{"name":{"value":"REDACTED FOR PRIVACY","count":92404141},"org":{"value":"REDACTED FOR PRIVACY","count":89136737},"street":{"value":"REDACTED FOR PRIVACY","count":87214024},"city":{"value":"REDACTED FOR PRIVACY","count":91124643},"state":{"value":"REDACTED FOR PRIVACY","count":87938445},"postal":{"value":"REDACTED FOR PRIVACY","count":92056029},"country":{"value":"REDACTED FOR PRIVACY","count":88204165},"phone":{"value":"","count":0},"fax":{"value":"","count":0},"email":[]},"create_date":{"value":"1998-08-02","count":881},"expiration_date":{"value":"2027-08-01","count":2111},"email_domain":[{"value":"enom.com","count":22145613},{"value":"nsone.net","count":4440523}],"soa_email":[{"value":"hostmaster@nsone.net","count":4884279}],"ssl_email":[],"additional_whois_email":[{"value":"abuse@enom.com","count":12707979}],"ip":[{"address":{"value":"199.30.228.112","count":4},"asn":[{"value":17318,"count":111}],"country_code":{"value":"US","count":292833707},"isp":{"value":"DomainTools LLC","count":222}}],"mx":[{"host":{"value":"aspmx.l.google.com","count":20042665},"domain":{"value":"google.com","count":23496110},"ip":[{"value":"74.125.142.26","count":3595011}],"priority":1},{"host":{"value":"aspmx3.googlemail.com","count":7072286},"domain":{"value":"googlemail.com","count":8166213},"ip":[{"value":"142.250.115.26","count":9090245}],"priority":10},{"host":{"value":"alt1.aspmx.l.google.com","count":19646081},"domain":{"value":"google.com","count":23496110},"ip":[{"value":"142.250.141.27","count":5621039}],"priority":5},{"host":{"value":"aspmx2.googlemail.com","count":7195048},"domain":{"value":"googlemail.com","count":8166213},"ip":[{"value":"142.250.141.27","count":5621039}],"priority":10},{"host":{"value":"alt2.aspmx.l.google.com","count":19558282},"domain":{"value":"google.com","count":23496110},"ip":[{"value":"142.250.115.26","count":9090245}],"priority":5},{"host":{"value":"aspmx4.googlemail.com","count":1534382},"domain":{"value":"googlemail.com","count":8166213},"ip":[{"value":"64.233.171.26","count":7395079}],"priority":10}],"name_server":[{"host":{"value":"dns4.p04.nsone.net","count":368900},"domain":{"value":"nsone.net","count":2983519},"ip":[{"value":"198.51.45.68","count":368871}]},{"host":{"value":"dns1.p04.nsone.net","count":367050},"domain":{"value":"nsone.net","count":2983519},"ip":[{"value":"198.51.44.4","count":367054}]},{"host":{"value":"dns2.p04.nsone.net","count":367056},"domain":{"value":"nsone.net","count":2983519},"ip":[{"value":"198.51.45.4","count":367057}]},{"host":{"value":"dns3.p04.nsone.net","count":366863},"domain":{"value":"nsone.net","count":2983519},"ip":[{"value":"198.51.44.68","count":366824}]}],"domain_risk":{"risk_score":0,"components":[{"name":"zerolist","risk_score":0}]},"redirect":{"value":"","count":0},"redirect_domain":{"value":"","count":0},"registrant_name":{"value":"REDACTED FOR PRIVACY","count":92696177},"registrant_org":{"value":"REDACTED FOR PRIVACY","count":35243392},"registrar":{"value":"ENOM, INC.","count":4040099},"registrar_status":["clienttransferprohibited"],"spf_info":"","ssl_info":[{"hash":{"value":"f8bf8d63eef2c146533bc705d78815a188db8dde","count":1},"subject":{"value":"CN=domaintools.com,O=DomainTools, LLC,ST=Washington,C=US,businessCategory=Private Organization,jurisdictionST=Delaware,jurisdictionC=US,serialNumber=4710432","count":1},"organization":{"value":"DomainTools, LLC","count":1},"email":[]}],"tld":"com","website_response":500,"data_updated_timestamp":"2022-06-09T16:05:01.373000","tags":[]}],"missing_domains":[]}
    """

    return json.loads(json_response)


def int_chase():
    json_response = """
    {
        "limit_exceeded":false,
        "has_more_results":false,
        "message":"Enjoy your data.",
        "results_count":1,
        "total_count":1,
        "results":[
        {
            "domain":"int-chase.com",
            "whois_url":"https://whois.domaintools.com/int-chase.com",
            "adsense":{
            "value":"",
            "count":0
            },
            "alexa":"",
            "popularity_rank":"",
            "active":false,
            "google_analytics":{
            "value":"",
            "count":0
            },
            "ga4":[
                {
                "value":"sample-ga4",
                "count":1
                }
            ],
            "gtm_codes":[

            ],
            "fb_codes":[

            ],
            "hotjar_codes":[

            ],
            "baidu_codes":[

            ],
            "yandex_codes":[

            ],
            "matomo_codes":[

            ],
            "statcounter_project_codes":[

            ],
            "statcounter_security_codes":[

            ],
            "admin_contact":{
            "name":{
                "value":"REACTIVATION PERIOD",
                "count":1480659
            },
            "org":{
                "value":"Withheld for Privacy Purposes",
                "count":757480
            },
            "street":{
                "value":"Kalkofnsvegur 2",
                "count":17138998
            },
            "city":{
                "value":"Reykjavik",
                "count":17170101
            },
            "state":{
                "value":"Capital Region",
                "count":31431601
            },
            "postal":{
                "value":"101",
                "count":17168860
            },
            "country":{
                "value":"is",
                "count":31496117
            },
            "phone":{
                "value":"3544212434",
                "count":17058585
            },
            "fax":{
                "value":"",
                "count":0
            },
            "email":[
                {
                "value":"reactivation-pending@mail.withheldforprivacy.com",
                "count":676164
                }
            ]
            },
            "billing_contact":{
            "name":{
                "value":"",
                "count":0
            },
            "org":{
                "value":"",
                "count":0
            },
            "street":{
                "value":"",
                "count":0
            },
            "city":{
                "value":"",
                "count":0
            },
            "state":{
                "value":"",
                "count":0
            },
            "postal":{
                "value":"",
                "count":0
            },
            "country":{
                "value":"",
                "count":0
            },
            "phone":{
                "value":"",
                "count":0
            },
            "fax":{
                "value":"",
                "count":0
            },
            "email":[

            ]
            },
            "registrant_contact":{
            "name":{
                "value":"REACTIVATION PERIOD",
                "count":1480659
            },
            "org":{
                "value":"Withheld for Privacy Purposes",
                "count":757480
            },
            "street":{
                "value":"Kalkofnsvegur 2",
                "count":17138998
            },
            "city":{
                "value":"Reykjavik",
                "count":17170101
            },
            "state":{
                "value":"Capital Region",
                "count":31431601
            },
            "postal":{
                "value":"101",
                "count":17168860
            },
            "country":{
                "value":"is",
                "count":31496117
            },
            "phone":{
                "value":"3544212434",
                "count":17058585
            },
            "fax":{
                "value":"",
                "count":0
            },
            "email":[
                {
                "value":"reactivation-pending@mail.withheldforprivacy.com",
                "count":677749
                }
            ]
            },
            "technical_contact":{
            "name":{
                "value":"REACTIVATION PERIOD",
                "count":1480659
            },
            "org":{
                "value":"Withheld for Privacy Purposes",
                "count":757480
            },
            "street":{
                "value":"Kalkofnsvegur 2",
                "count":17138998
            },
            "city":{
                "value":"Reykjavik",
                "count":17170101
            },
            "state":{
                "value":"Capital Region",
                "count":31431601
            },
            "postal":{
                "value":"101",
                "count":17168860
            },
            "country":{
                "value":"is",
                "count":31496117
            },
            "phone":{
                "value":"3544212434",
                "count":17058585
            },
            "fax":{
                "value":"",
                "count":0
            },
            "email":[
                {
                "value":"reactivation-pending@mail.withheldforprivacy.com",
                "count":676094
                }
            ]
            },
            "create_date":{
            "value":"2020-10-13",
            "count":197233
            },
            "expiration_date":{
            "value":"2021-10-13",
            "count":118439
            },
            "email_domain":[
            {
                "value":"namecheap.com",
                "count":49448705
            },
            {
                "value":"mail.withheldforprivacy.com",
                "count":677799
            }
            ],
            "soa_email":[
            {
                "value":"hostmaster@int-chase.com",
                "count":1
            }
            ],
            "ssl_email":[

            ],
            "additional_whois_email":[
            {
                "value":"abuse@namecheap.com",
                "count":47787232
            }
            ],
            "ip":[
            {
                "address":{
                "value":"99.83.154.118",
                "count":9194795
                },
                "asn":[
                {
                    "value":16509,
                    "count":120416120
                }
                ],
                "country_code":{
                "value":"us",
                "count":195643825
                },
                "isp":{
                "value":"Amazon.com Inc.",
                "count":43009293
                }
            }
            ],
            "mx":[

            ],
            "name_server":[
            {
                "host":{
                "value":"dns1.registrar-servers.com",
                "count":18853595
                },
                "domain":{
                "value":"registrar-servers.com",
                "count":38839846
                },
                "ip":[
                {
                    "value":"156.154.132.200",
                    "count":20374945
                }
                ]
            },
            {
                "host":{
                "value":"dns101.registrar-servers.com",
                "count":27709179
                },
                "domain":{
                "value":"registrar-servers.com",
                "count":38839846
                },
                "ip":[
                {
                    "value":"13.248.239.149",
                    "count":9512650
                }
                ]
            },
            {
                "host":{
                "value":"dns102.registrar-servers.com",
                "count":27708905
                },
                "domain":{
                "value":"registrar-servers.com",
                "count":38839846
                },
                "ip":[
                {
                    "value":"76.223.108.9",
                    "count":9512767
                }
                ]
            },
            {
                "host":{
                "value":"dns2.registrar-servers.com",
                "count":18853215
                },
                "domain":{
                "value":"registrar-servers.com",
                "count":38839846
                },
                "ip":[
                {
                    "value":"156.154.133.200",
                    "count":20374896
                }
                ]
            }
            ],
            "domain_risk":{
            "risk_score":71,
            "components":[
                {
                "name":"proximity",
                "risk_score":38
                },
                {
                "name":"threat_profile",
                "risk_score":71,
                "threats":[
                    "spam"
                ],
                "evidence":[
                    "registrant",
                    "domain name",
                    "name server"
                ]
                },
                {
                "name":"threat_profile_malware",
                "risk_score":25
                },
                {
                "name":"threat_profile_phishing",
                "risk_score":68
                },
                {
                "name":"threat_profile_spam",
                "risk_score":71,
                "threats":[
                    "spam"
                ]
                }
            ]
            },
            "redirect":{
            "value":"www.chase.com",
            "count":333
            },
            "redirect_domain":{
            "value":"chase.com",
            "count":453
            },
            "registrant_name":{
            "value":"REACTIVATION PERIOD",
            "count":1483945
            },
            "registrant_org":{
            "value":"Withheld for Privacy Purposes",
            "count":757609
            },
            "registrar":{
            "value":"NAMECHEAP INC",
            "count":18144909
            },
            "registrar_status":[
            "clienttransferprohibited",
            "redemptionperiod"
            ],
            "spf_info":"",
            "ssl_info":[
            {
                "hash":{
                "value":"195152d01022a568719e7bc1d0b07c13f723934f",
                "count":1
                },
                "subject":{
                "value":"CN=int-chase.com",
                "count":1
                },
                "organization":{
                "value":"",
                "count":0
                },
                "email":[

                ],
                "alt_names":[
                {
                    "value":"webmail.int-chase.com",
                    "count":0
                },
                {
                    "value":"cpanel.int-chase.com",
                    "count":0
                },
                {
                    "value":"webdisk.int-chase.com",
                    "count":0
                },
                {
                    "value":"int-chase.com",
                    "count":0
                },
                {
                    "value":"mail.int-chase.com",
                    "count":0
                },
                {
                    "value":"www.int-chase.com",
                    "count":0
                }
                ],
                "sources":{
                "active":1650844800000
                },
                "common_name":{
                "value":"int-chase.com",
                "count":1
                },
                "issuer_common_name":{
                "value":"Let's Encrypt Authority X3",
                "count":13909637
                },
                "not_after":{
                "value":20200114,
                "count":71104
                },
                "not_before":{
                "value":20191016,
                "count":66365
                },
                "duration":{
                "value":91,
                "count":63753496
                }
            }
            ],
            "tld":"com",
            "website_response":403,
            "data_updated_timestamp":"2023-09-15T07:40:27.892000",
            "website_title":"",
            "server_type":"",
            "first_seen":{
            "value":"2020-10-13T00:00:00Z",
            "count":0
            },
            "tags":[
            {
                "label":"blocklist",
                "scope":"group",
                "tagged_at":"2023-09-13T14:59:07Z"
            }
            ]
        }
        ],
        "missing_domains":[

        ]
    }
    """
    return json.loads(json_response)
